import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "simple-motion-graphics",
    video_title: "Minimalist Motion Graphics",
    video_description: "A clean, elegant motion graphics piece created in After Effects demonstrating fluid shape animations, smooth easing, and modern minimalist design aesthetics.",
    tags: ["Motion Graphics", "After Effects", "Shape Animation", "Minimalist"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/thumbnails/Screenshot%202026-09-11%20160617.png",
    publish_date: "2026-09-10",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/After-effects/motion%20graphics.mp4",
    project_images: [],
    category: ["After Effects"],
    software_used: ["After Effects"],
  },
  {
    id: "3d-text-animation",
    video_title: "Cinematic 3D Text Animation",
    video_description: "A dynamic 3D kinetic typography piece in After Effects exploring spatial depth, camera motion, lighting effects, and rhythmic text animations.",
    tags: ["3D Text", "Kinetic Typography", "After Effects", "Animation"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/thumbnails/Screenshot%202026-09-11%20161503.png",
    publish_date: "2026-09-09",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/After-effects/3d%20text%20animation.mp4",
    project_images: [],
    category: ["After Effects"],
    software_used: ["After Effects"],
  },
  {
    id: "motion-graphics-2",
    video_title: "Dynamic Vector Motion Graphics",
    video_description: "An engaging visual exploration of vector motion graphics, seamless shape transitions, and modern UI motion design elements.",
    tags: ["Motion Graphics", "Vector Animation", "Transitions", "After Effects"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/thumbnails/Screenshot%202026-09-11%20161436.png",
    publish_date: "2026-09-08",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/After-effects/motion%20graphics%202.mp4",
    project_images: [],
    category: ["After Effects"],
    software_used: ["After Effects"],
  },
  {
    id: "colour-grading-reel",
    video_title: "Cinematic Color Grading Showcase",
    video_description: "A professional color grading showcase in DaVinci Resolve highlighting color space transforms, rich filmic contrast, skin tone accuracy, and atmospheric mood enhancement.",
    tags: ["Color Grading", "DaVinci Resolve", "Cinematic", "Color Correction"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/thumbnails/Screenshot%202026-09-11%20160650.png",
    publish_date: "2026-09-07",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Davinci/colour%20grading.mp4",
    project_images: [],
    category: ["DaVinci Resolve"],
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "dodge-vector-design",
    video_title: "Dodge Challenger Vector Art",
    video_description: "A highly detailed vector illustration of a classic Dodge Challenger designed in Adobe Illustrator with precise paths, custom gradients, and realistic lighting highlights.",
    tags: ["Vector Design", "Illustrator", "Automotive Art", "Graphic Design"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Illustrator/dodge.jpg",
    publish_date: "2026-09-06",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Illustrator/dodge.jpg"],
    category: ["Illustrator"],
    software_used: ["Illustrator"],
  },
  {
    id: "red-bun-vector-design",
    video_title: "Red Bun Character Vector Design",
    video_description: "A vibrant, stylized vector character design exploring expressive artwork, bold color palettes, clean outlines, and digital vector illustration techniques.",
    tags: ["Character Design", "Vector Art", "Illustrator", "Graphic Design"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Illustrator/redbun.jpg",
    publish_date: "2026-09-05",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Illustrator/redbun.jpg"],
    category: ["Illustrator"],
    software_used: ["Illustrator"],
  },
  {
    id: "fast-paced-montage-edit",
    video_title: "High-Energy Fast Paced Video Edit",
    video_description: "A high-tempo video montage featuring rhythmic cut-ons, speed ramps, sound design synchronization, and eye-catching visual emphasis.",
    tags: ["Fast Paced Edit", "Montage", "Premiere Pro", "After Effects"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/thumbnails/Screenshot%202026-09-11%20160529.png",
    publish_date: "2026-09-04",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Premier-pro/fast%20paced%20edit.mp4",
    project_images: [],
    category: ["Premiere Pro", "After Effects"],
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "flying-ship-photo-manipulation",
    video_title: "Flying Ship Photo Manipulation",
    video_description: "A surreal fantasy photo manipulation created in Adobe Photoshop combining multiple stock assets, custom lighting atmosphere, seamless blending, and matte painting.",
    tags: ["Photo Manipulation", "Photoshop", "Surreal Art", "Matte Painting"],
    cover_image: "https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Photoshop/flying%20ship.jpg",
    publish_date: "2026-09-03",
    client_name: "Personal Project",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "",
    project_images: ["https://pub-78840538994f48aa9dc0057cf1e91755.r2.dev/Photoshop/flying%20ship.jpg"],
    category: ["Photoshop"],
    software_used: ["Photoshop"],
  },
];
